/**
 * Escenas reales de Cuenca, Quito y Guayaquil (Wikimedia Commons) para las galerías de las personas demo de Ecuador.
 * Se sirven como miniaturas estándar de Commons (960 px y 330 px). Todas son licencias libres (CC BY, CC BY-SA o CC0):
 * si las muestras en un sitio público, acredita al autor con el enlace de `pagina`. Verificadas con HTTP 200 al generarlas.
 * Retratos: pravatar.cc (imágenes de muestra para avatares); ver `RETRATOS` en personas.ts.
 */
export interface Escena {
  url: string;
  miniatura: string;
  pagina: string;
  licencia: string;
  autor: string;
}

export const ESCENAS: Record<string, Escena> = {
  "cuenca-catedral": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca.jpg/960px-Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca.jpg/330px-Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Catedral_de_la_Inmaculada_Concepci%C3%B3n,_Cuenca.jpg", licencia: "CC BY-SA 3.0", autor: "Bernard Gagnon" },
  "cuenca-tomebamba": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/R%C3%ADo_Tomebamba_desde_el_Paseo_3_de_Noviembre%2C_Cuenca.jpg/960px-R%C3%ADo_Tomebamba_desde_el_Paseo_3_de_Noviembre%2C_Cuenca.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/R%C3%ADo_Tomebamba_desde_el_Paseo_3_de_Noviembre%2C_Cuenca.jpg/330px-R%C3%ADo_Tomebamba_desde_el_Paseo_3_de_Noviembre%2C_Cuenca.jpg", pagina: "https://commons.wikimedia.org/wiki/File:R%C3%ADo_Tomebamba_desde_el_Paseo_3_de_Noviembre,_Cuenca.jpg", licencia: "CC BY-SA 4.0", autor: "Martín Vasco" },
  "cuenca-turi-cafe": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Mirador_de_Turi_Ecuador_1739.jpg/960px-Mirador_de_Turi_Ecuador_1739.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Mirador_de_Turi_Ecuador_1739.jpg/330px-Mirador_de_Turi_Ecuador_1739.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Mirador_de_Turi_Ecuador_1739.jpg", licencia: "CC BY 4.0", autor: "Arabsalam" },
  "cuenca-arcos": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca_04.jpg/960px-Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca_04.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca_04.jpg/330px-Catedral_de_la_Inmaculada_Concepci%C3%B3n%2C_Cuenca_04.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Catedral_de_la_Inmaculada_Concepci%C3%B3n,_Cuenca_04.jpg", licencia: "CC BY-SA 3.0", autor: "Bernard Gagnon" },
  "cuenca-turi-mirador": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Mirador_de_Turi_Ecuador_1736.jpg/960px-Mirador_de_Turi_Ecuador_1736.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Mirador_de_Turi_Ecuador_1736.jpg/330px-Mirador_de_Turi_Ecuador_1736.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Mirador_de_Turi_Ecuador_1736.jpg", licencia: "CC BY 4.0", autor: "Arabsalam" },
  "cuenca-turi-valle": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Mirador_de_Turi_Ecuador_1742.jpg/960px-Mirador_de_Turi_Ecuador_1742.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Mirador_de_Turi_Ecuador_1742.jpg/330px-Mirador_de_Turi_Ecuador_1742.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Mirador_de_Turi_Ecuador_1742.jpg", licencia: "CC BY 4.0", autor: "Arabsalam" },
  "cuenca-rio-piedras": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Rio_Tomebamba_con_un_caudal_bajo_durante_el_estiaje_de_2024.jpg/960px-Rio_Tomebamba_con_un_caudal_bajo_durante_el_estiaje_de_2024.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Rio_Tomebamba_con_un_caudal_bajo_durante_el_estiaje_de_2024.jpg/330px-Rio_Tomebamba_con_un_caudal_bajo_durante_el_estiaje_de_2024.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Rio_Tomebamba_con_un_caudal_bajo_durante_el_estiaje_de_2024.jpg", licencia: "CC BY-SA 4.0", autor: "Martin.vascovinueza" },
  "cuenca-turi-panoramica": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Panor%C3%A1mica_desde_Turi_de_Cuenca_%28Ecuador%29_2.jpg/960px-Panor%C3%A1mica_desde_Turi_de_Cuenca_%28Ecuador%29_2.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Panor%C3%A1mica_desde_Turi_de_Cuenca_%28Ecuador%29_2.jpg/330px-Panor%C3%A1mica_desde_Turi_de_Cuenca_%28Ecuador%29_2.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Panor%C3%A1mica_desde_Turi_de_Cuenca_(Ecuador)_2.jpg", licencia: "CC BY 3.0", autor: "PAULOGARCIA2005" },
  "quito-floresta": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Motorcycle_in_La_Floresta%2C_Quito.jpg/960px-Motorcycle_in_La_Floresta%2C_Quito.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Motorcycle_in_La_Floresta%2C_Quito.jpg/330px-Motorcycle_in_La_Floresta%2C_Quito.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Motorcycle_in_La_Floresta,_Quito.jpg", licencia: "CC BY 4.0", autor: "Theodore.shouse" },
  "quito-garcia-moreno": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Quito_calle_Garc%C3%ADa_Moreno.jpg/960px-Quito_calle_Garc%C3%ADa_Moreno.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Quito_calle_Garc%C3%ADa_Moreno.jpg/330px-Quito_calle_Garc%C3%ADa_Moreno.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Quito_calle_Garc%C3%ADa_Moreno.jpg", licencia: "CC BY-SA 3.0", autor: "Cayambe" },
  "quito-santo-domingo": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Iglesia_de_Santo_Domingo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_202-204_HDR.JPG/960px-Iglesia_de_Santo_Domingo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_202-204_HDR.JPG", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Iglesia_de_Santo_Domingo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_202-204_HDR.JPG/330px-Iglesia_de_Santo_Domingo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_202-204_HDR.JPG", pagina: "https://commons.wikimedia.org/wiki/File:Iglesia_de_Santo_Domingo,_Quito,_Ecuador,_2015-07-22,_DD_202-204_HDR.JPG", licencia: "CC BY-SA 4.0", autor: "Diego Delso" },
  "quito-atardecer": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Llovizna_al_atardecer_-_panoramio.jpg/960px-Llovizna_al_atardecer_-_panoramio.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Llovizna_al_atardecer_-_panoramio.jpg/330px-Llovizna_al_atardecer_-_panoramio.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Llovizna_al_atardecer_-_panoramio.jpg", licencia: "CC BY-SA 3.0", autor: "Cristian Paliz" },
  "quito-teleferico-vista": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg/960px-Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg/330px-Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg", licencia: "CC BY 2.0", autor: "David Berkowitz" },
  "quito-gondolas": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg/960px-Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg/330px-Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Gondolas_of_the_TeleferiQo_in_Quito,_Ecuador.jpg", licencia: "CC BY-SA 4.0", autor: "AndrewDressel" },
  "quito-biblioteca": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Museo_de_la_Catedral_de_Quito%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_94-96_HDR.JPG/960px-Museo_de_la_Catedral_de_Quito%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_94-96_HDR.JPG", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Museo_de_la_Catedral_de_Quito%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_94-96_HDR.JPG/330px-Museo_de_la_Catedral_de_Quito%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_94-96_HDR.JPG", pagina: "https://commons.wikimedia.org/wiki/File:Museo_de_la_Catedral_de_Quito,_Quito,_Ecuador,_2015-07-22,_DD_94-96_HDR.JPG", licencia: "CC BY-SA 4.0", autor: "Diego Delso" },
  "quito-estacion": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Top_station_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg/960px-Top_station_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Top_station_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg/330px-Top_station_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Top_station_of_the_TeleferiQo_in_Quito,_Ecuador.jpg", licencia: "CC BY-SA 4.0", autor: "AndrewDressel" },
  "gye-puerto-santa-ana": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Puerto_Santa_Ana._Guayaquil%2C_Guayas%2C_Ecuador.jpg/960px-Puerto_Santa_Ana._Guayaquil%2C_Guayas%2C_Ecuador.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Puerto_Santa_Ana._Guayaquil%2C_Guayas%2C_Ecuador.jpg/330px-Puerto_Santa_Ana._Guayaquil%2C_Guayas%2C_Ecuador.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Puerto_Santa_Ana._Guayaquil,_Guayas,_Ecuador.jpg", licencia: "CC0", autor: "Unknown authorUnknown author" },
  "gye-callejones": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/SageoEG_-_Puerto_Santa_Ana_-_Callejones_06.jpg/960px-SageoEG_-_Puerto_Santa_Ana_-_Callejones_06.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/SageoEG_-_Puerto_Santa_Ana_-_Callejones_06.jpg/330px-SageoEG_-_Puerto_Santa_Ana_-_Callejones_06.jpg", pagina: "https://commons.wikimedia.org/wiki/File:SageoEG_-_Puerto_Santa_Ana_-_Callejones_06.jpg", licencia: "CC BY-SA 3.0", autor: "Sageo" },
  "gye-malecon": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Vista_del_Malec%C3%B3n_2000.jpg/960px-Vista_del_Malec%C3%B3n_2000.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Vista_del_Malec%C3%B3n_2000.jpg/330px-Vista_del_Malec%C3%B3n_2000.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Vista_del_Malec%C3%B3n_2000.jpg", licencia: "CC BY-SA 4.0", autor: "Freddy eduardo" },
  "gye-las-penas": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Abril_2005_029.jpg/960px-Abril_2005_029.jpg", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Abril_2005_029.jpg/330px-Abril_2005_029.jpg", pagina: "https://commons.wikimedia.org/wiki/File:Abril_2005_029.jpg", licencia: "CC BY 3.0", autor: "Epiovesan" },
  "gye-capilla": { url: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Capilla_Santa_Ana_desde_el_Faro.JPG/960px-Capilla_Santa_Ana_desde_el_Faro.JPG", miniatura: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Capilla_Santa_Ana_desde_el_Faro.JPG/330px-Capilla_Santa_Ana_desde_el_Faro.JPG", pagina: "https://commons.wikimedia.org/wiki/File:Capilla_Santa_Ana_desde_el_Faro.JPG", licencia: "CC BY-SA 4.0", autor: "Edjoerv" },
};
