import type { Propiedad } from "@/types/propiedad";

const img = (id: string) =>
  `https://images.unsplash.com/${id}?w=900&q=80&auto=format&fit=crop`;

// Propiedades de ejemplo (las publicadas por usuarios viven en el estado de la app).
export const PROPIEDADES: Propiedad[] = [
  {
    id: "1",
    titulo: "Casa moderna con jardín",
    descripcion:
      "Amplia casa de dos plantas con jardín, garaje doble y acabados de primera calidad.",
    tipo: "casa",
    operacion: "venta",
    precio: 320000,
    moneda: "USD",
    ubicacion: "Zona Norte",
    dormitorios: 4,
    banos: 3,
    superficie: 220,
    imagen: img("photo-1568605114967-8130f3a36994"),
    comodidades: ["Jardín", "Garaje", "Parrilla"],
    duenoId: "u1",
    publicadaHace: 1,
    guardados: 34,
  },
  {
    id: "2",
    titulo: "Departamento céntrico luminoso",
    descripcion:
      "Departamento de 2 ambientes con balcón, a pasos del transporte y comercios.",
    tipo: "departamento",
    operacion: "alquiler",
    precio: 850,
    moneda: "USD",
    ubicacion: "Centro",
    dormitorios: 2,
    banos: 1,
    superficie: 68,
    imagen: img("photo-1502672260266-1c1ef2d93688"),
    comodidades: ["Balcón", "Wifi", "Aire acondicionado"],
    duenoId: "u2",
    publicadaHace: 3,
    guardados: 21,
    relampago: 10,
  },
  {
    id: "3",
    titulo: "Terreno en zona residencial",
    descripcion:
      "Lote plano listo para construir, con todos los servicios y escritura al día.",
    tipo: "terreno",
    operacion: "venta",
    precio: 95000,
    moneda: "USD",
    ubicacion: "Zona Sur",
    dormitorios: 0,
    banos: 0,
    superficie: 450,
    imagen: img("photo-1500382017468-9049fed747ef"),
    comodidades: ["Servicios", "Escritura al día"],
    duenoId: "u3",
    publicadaHace: 12,
    guardados: 8,
  },
  {
    id: "4",
    titulo: "Villa contemporánea con piscina",
    descripcion:
      "Villa de diseño con piscina, amplios ventanales, cocina abierta y zona de barbacoa.",
    tipo: "villa",
    operacion: "venta",
    precio: 540000,
    moneda: "USD",
    ubicacion: "Las Lomas",
    dormitorios: 5,
    banos: 4,
    superficie: 380,
    imagen: img("photo-1512917774080-9991f1c4c750"),
    comodidades: ["Piscina", "Parrilla", "Garaje", "Seguridad 24 h"],
    duenoId: "u4",
    publicadaHace: 2,
    guardados: 52,
  },
  {
    id: "5",
    titulo: "Loft de diseño con doble altura",
    descripcion:
      "Loft reformado con techos altos, mucha luz natural y cocina integrada. Ideal para una persona o pareja.",
    tipo: "departamento",
    operacion: "alquiler",
    precio: 1100,
    moneda: "USD",
    ubicacion: "Barrio Histórico",
    dormitorios: 1,
    banos: 1,
    superficie: 75,
    imagen: img("photo-1522708323590-d24dbb6b0267"),
    comodidades: ["Wifi", "Amoblado", "Pet friendly"],
    duenoId: "u5",
    publicadaHace: 0,
    guardados: 15,
  },
  {
    id: "6",
    titulo: "Departamento con vistas a la ciudad",
    descripcion:
      "Piso 14 con vistas despejadas, cochera y amenities: gimnasio, SUM y terraza.",
    tipo: "departamento",
    operacion: "venta",
    precio: 185000,
    moneda: "USD",
    ubicacion: "Puerto Nuevo",
    dormitorios: 2,
    banos: 2,
    superficie: 92,
    imagen: img("photo-1493809842364-78817add7ffb"),
    comodidades: ["Gimnasio", "Terraza", "Cochera"],
    duenoId: "u6",
    publicadaHace: 6,
    guardados: 27,
  },
  {
    id: "7",
    titulo: "Casa familiar en barrio cerrado",
    descripcion:
      "Casa de tres plantas en barrio cerrado con seguridad 24 h, parque y club house.",
    tipo: "casa",
    operacion: "alquiler",
    precio: 2400,
    moneda: "USD",
    ubicacion: "Country Los Pinos",
    dormitorios: 4,
    banos: 3,
    superficie: 260,
    imagen: img("photo-1600585154340-be6161a56a0c"),
    comodidades: ["Seguridad 24 h", "Club house", "Jardín", "Pet friendly"],
    duenoId: "u7",
    publicadaHace: 4,
    guardados: 19,
  },
  {
    id: "8",
    titulo: "Residencia clásica con gran parque",
    descripcion:
      "Residencia señorial rodeada de jardines, con galería, biblioteca y casa de huéspedes.",
    tipo: "casa",
    operacion: "venta",
    precio: 890000,
    moneda: "USD",
    ubicacion: "Valle Alto",
    dormitorios: 6,
    banos: 5,
    superficie: 620,
    imagen: img("photo-1580587771525-78b9dba3b914"),
    comodidades: ["Jardín", "Casa de huéspedes", "Biblioteca", "Garaje"],
    duenoId: "u8",
    publicadaHace: 9,
    guardados: 41,
  },
];

export const COMODIDADES_SUGERIDAS = [
  "Wifi",
  "Piscina",
  "Jardín",
  "Garaje",
  "Parrilla",
  "Aire acondicionado",
  "Amoblado",
  "Pet friendly",
  "Balcón",
  "Seguridad 24 h",
  "Gimnasio",
  "Terraza",
];

export const ZONAS = [
  "Zona Norte",
  "Centro",
  "Zona Sur",
  "Las Lomas",
  "Barrio Histórico",
  "Puerto Nuevo",
  "Country Los Pinos",
  "Valle Alto",
];
